### ISSUE TITLE
[Bug] Windows平台打包时会有文件名大小写敏感的问题

### ISSUE THREAD

**Issue by Andy-Chuck** [BalloonUpdate/McPatchClient#1]
复现流程：把 workspace mods目录里的 Spark.jar 重命名为 spark.jar 。

![1](https://user-images.githubusercontent.com/54295429/211238663-952bd64d-3263-4183-b51c-21b0557c2c68.png)
![2](https://user-images.githubusercontent.com/54295429/211238689-e2c93996-304c-4797-87f5-3b22553ba8a6.png)
![3](https://user-images.githubusercontent.com/54295429/211238777-b242812e-9213-48fc-a730-c095650ee2d9.png)
![4](https://user-images.githubusercontent.com/54295429/211238988-9145a37a-d071-40f7-85dc-6df6a91b2774.png)
工作目录 服务端 客户端的版本号都正常，但客户端mod文件夹内的spark.jar却被删除

下面是客户端的日志，服务端有2个版本，应该是更新第2个版本时出的问题

> [ 01-09 11:46:19.751 INFO  ] [McPatchClient] RAM: 26.25 MB
[ 01-09 11:46:19.753 INFO  ] [McPatchClient] Graphics Mode: true
[ 01-09 11:46:19.753 INFO  ] [McPatchClient] Standalone: false
[ 01-09 11:46:19.753 INFO  ] [McPatchClient] Updating Directory:   C:/Users/i/Desktop/***
[ 01-09 11:46:19.754 INFO  ] [McPatchClient] Working Directory:    C:/Users/i/Desktop/***/.minecraft/versions/***-1.16.5
[ 01-09 11:46:19.754 INFO  ] [McPatchClient] Executable Directory: C:/Users/i/Desktop/***/.minecraft/versions/***-1.16.5
[ 01-09 11:46:19.768 INFO  ] [McPatchClient] Application Version:  1.0.12 (0a927c6cf0726e5e92acdcf86e89d9c38896dc67)
[ 01-09 11:46:19.769 INFO  ] [McPatchClient] Java virtual Machine: Oracle Corporation 1.8.0_351
[ 01-09 11:46:19.769 INFO  ] [McPatchClient] Operating System: Windows 11 10.0 amd64
[ 01-09 11:46:22.136 DEBUG ] [McPatchClient] http request on https://files.***/d/MCUpdate/test/mc-patch-versions.txt
[ 01-09 11:46:24.060 DEBUG ] [McPatchClient] all versions: 
[ 01-09 11:46:24.060 DEBUG ] [McPatchClient]   - BasePack
[ 01-09 11:46:24.060 DEBUG ] [McPatchClient]   - 230109
[ 01-09 11:46:24.061 INFO  ] [McPatchClient] current version: none, newest version: 230109
[ 01-09 11:46:24.061 INFO  ] [McPatchClient] missing versions: [BasePack, 230109]
[ 01-09 11:46:24.061 DEBUG ] [McPatchClient] http request on https://files.***/d/MCUpdate/test/BasePack.mc-patch.json
[ 01-09 11:46:24.705 DEBUG ] [McPatchClient] http request on https://files.***/d/MCUpdate/test/230109.mc-patch.json
[ 01-09 11:46:25.449 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/AutoRegLib.jar|f||921cf73b9d31bce5d332115a5144c3fca2010f93||5b01baf7302d698d69383f7ab5b8c5b596d3f2d1|bd|c81f|dfbf
[ 01-09 11:46:25.450 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Cloth-config.jar|f||422e4f65872bf8babfa139094b7cb242e9f9f434||b5f147963d4345c2ee09f9d9e3eb7c54f2d1f387|c99b|13bee1|15fe9e
[ 01-09 11:46:25.450 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/CustomNPCs.jar|f||868c476be34bac92bc4f98d864a8d62c3792817d||3b9cfab330f395137c2454ff8a9bf90aa0c2a689|148939|b67aa5|be15ae
[ 01-09 11:46:25.450 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Dads_sewing.jar|f||d8ea56bbce822d2d29dd3777c51a850cf3f83016||6f9387760b09cb32ee4324d6355fc5f14def60af|cb049c|33f41|55d47
[ 01-09 11:46:25.451 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Drinkbeer.jar|f||6b06f6e1aba859e0a7a2f4b9912a99c46b1ee32b||e990112b304224a7f0667fa075043fe8732101eb|ce4499|dbeeb|e3ea3
[ 01-09 11:46:25.451 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Etched-forge.jar|f||85a69264ea32035207f19e9e40a3f0d75cc701d4||e86dd1a15a9ea27e80d82eb3e8f62b0c52904146|dc0443|83c75|9b9e2
[ 01-09 11:46:25.452 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/FarmersDelight.jar|f||006e441f80aa2c97787cf9b968926a6b2eb22470||cc5d3e5939808eee790420781c320c56c78f4fa9|e44179|225dd7|272461
[ 01-09 11:46:25.452 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/i18nupdatemod.jar|f||1131309fb6680bfe0cc0301305666beed65fea29||b5f4eeb53c6ce1b7685aab33f318b83e2c3fc19b|106a010|1923|1ca8
[ 01-09 11:46:25.453 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Jei.jar|f||c584e55cb8c117e888a80ccc6e5007f104915d2f||b4b5e2c48e271b1f636310f67370417b9e627725|106b9e9|b3d9d|c5aac
[ 01-09 11:46:25.453 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Jeiintegration.jar|f||681c6a8ac2e7e095c613d776411eec06e160cb5b||6c707540cfb10b04cbc970ee2a30efe5d548c0f9|111f847|5d00|618b
[ 01-09 11:46:25.453 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Journeymap.jar|f||5245221653a0113713a7261898b49f71b779b6c8||a2f8c2ee072676b228f2f8f8e2e3237b0c341421|1125604|5d0ff8|6622d9
[ 01-09 11:46:25.453 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/JustEnoughCharacters.jar|f||48a0f80506254801f3e05d6eee605568c9664bf1||a33c38448fd4eedd48cafbb0b53f167c6d9d4014|16f66c3|3836a|3c38f
[ 01-09 11:46:25.454 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/JustEnoughResources.jar|f||76386ca11a7305f740d13d43f42bed2b3b7d5d86||5c6eb65a30cb8849a3ba3a2b294f4308c7ffe639|172eaf3|348e3|3928e
[ 01-09 11:46:25.454 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Mantle.jar|f||61cd1d256a29445d153bd076e090f6172eff2aff||cccdd10fd5a09ead3dfce0ded359f3aa0c2df8f6|176348f|b4050|c4f51
[ 01-09 11:46:25.454 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Mcw-furniture.jar|f||0d3c0b9edeb10c1a3d31c8959cad40e3f6d26c08||daa863fa03b9ee0e194466cc81c549cf07398f0a|181759f|a6770|1625b3
[ 01-09 11:46:25.454 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Minecolonies.jar|f||b8910bac145573bccf2448497a4021ef5dc6fced||38d43bd2f467544071de39a988afb8090e8b9a10|18bddce|243f44e|268bca4
[ 01-09 11:46:25.455 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Paladin.jar|f||03de215f58ae2bdfa79ee68501375c401bfd802f||3b07a77acaa1439d43346309462b867a58302783|3cfd2d6|275773|4bc994
[ 01-09 11:46:25.455 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Pollen-forge.jar|f||26c61ac362381ac1675ed9b01a583765628cca1a||57792762b11d310a15e39d990ff6636e59d96d60|3f72b08|105f76|1346a7
[ 01-09 11:46:25.455 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Quark.jar|f||c314a534737baba9416c4947e15f81c6243f9844||fdb1b26caeec59929b4d30e65d60228e2fcd6ebf|4078b36|6d2353|863ae5
[ 01-09 11:46:25.455 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Spark.jar|f||e535ad75bb2f541ea8c9ad3fda5da9b3241c2575||824253196ca8102b3198110b87b6099e73d79507|474af41|2ce6b2|302c59
[ 01-09 11:46:25.456 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Structurize.jar|f||15e49e336b102c5aaaaa69cd43b75d955371211f||32fbfa4de2d9c909e47b65b253f9255e4354004d|4a196b1|481259|ae187d
[ 01-09 11:46:25.456 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/TConstruct.jar|f||c0247535cacd84d283d5294efb8f9c0f5cbf28a2||2343a26bd0c19775ce7687b388a403e9bf244e9a|4e9a9c7|7416e9|a4e42d
[ 01-09 11:46:25.456 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Tinker_rapier.jar|f||38cf7b45becfebb68e9c92f59ea3cf2afb5f2512||a9d62fa71bf584df22e0806d818641633a7a7611|55dc170|aeb6|1b44b
[ 01-09 11:46:25.457 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/TinyChests.jar|f||c15c90685d0b41b129fc3e41831a9132c28dfe47||426aadbf047d153bd4552b043b90cfe015bf5f55|55e70e3|1ace2|25ba7
[ 01-09 11:46:25.457 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Towers_of_the_wild.jar|f||585e3a64b9de628e7dbd53e7c2f812ccdfd4f5a2||99bb976d6ddd1195de3b15129f81bd7a4bcdbd96|5601e8a|23913|265fd
[ 01-09 11:46:25.457 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/TwilightDelight.jar|f||534ddf98c900637cdffb7ffc33a91b1bbf782964||2999d958f3718bef3a90157f83e0971e7e0f2881|562585f|1c7e3|2ecdf
[ 01-09 11:46:25.458 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Twilightforest.jar|f||05c891e265be9688a945e4d0298b1fb1ebb66947||bb40844d077dcb95f8249fd654499eb66d957f3d|5642103|1d14fcb|1e344bb
[ 01-09 11:46:25.458 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Waystones.jar|f||c1e9a42ea6f2ca542a98714706fa69725388d10f||8f2ca56d316acb276ca80a392ef14e9ae4fb004b|735718a|4e68c|5bb3a
[ 01-09 11:46:25.458 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/WegotRunners.jar|f||b557656eaa6613094901cf8b52eeb0a9bb9b761f||e8ed76d5b4715a82023f9d0e30fca138c0b8e578|73a58d5|22cb4|2695f
[ 01-09 11:46:25.458 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Worldedit.jar|f||9524fbe78c31228f80730313df3abbc7bfebc77c||023ac497ccd7095fb7f2001ef8f0e165166425b7|73c8645|4c6d2b|5110ff
[ 01-09 11:46:25.459 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/mods/Wyrmroost.jar|f||1544dd74be53399285bb52663bb30a76e281dd42||cd3a14e512fefad89ff6ef24916e2c862180995b|788f42c|49ff30|4bcc18
[ 01-09 11:46:25.459 DEBUG ] [McPatchClient/BasePack] new files: .minecraft/versions/***-1.16.5/servers.dat|f||f6688a5e592a18597ed58eeed0d9e67beadeb26a||469c7c05937563200f484e10c532a725f903c532|7d2f411|59|3d
[ 01-09 11:46:25.459 DEBUG ] [McPatchClient/BasePack] new dirs:  .minecraft
[ 01-09 11:46:25.459 DEBUG ] [McPatchClient/BasePack] new dirs:  .minecraft/versions
[ 01-09 11:46:25.460 DEBUG ] [McPatchClient/BasePack] new dirs:  .minecraft/versions/***-1.16.5
[ 01-09 11:46:25.460 DEBUG ] [McPatchClient/BasePack] new dirs:  .minecraft/versions/***-1.16.5/mods
[ 01-09 11:46:25.463 DEBUG ] [McPatchClient/BasePack] http request on https://files.***/d/MCUpdate/test/BasePack.mc-patch.bin, write to: C:/Users/i/AppData/Local/Temp/mc-patch-BasePack7065019544649574349.bin
[ 01-09 11:47:40.821 DEBUG ] [McPatchClient/BasePack] calculating the hash of the patch file
[ 01-09 11:47:51.451 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/AutoRegLib.jar
[ 01-09 11:47:51.456 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Cloth-config.jar
[ 01-09 11:47:51.592 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/CustomNPCs.jar
[ 01-09 11:47:52.641 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Dads_sewing.jar
[ 01-09 11:47:52.669 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Drinkbeer.jar
[ 01-09 11:47:52.750 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Etched-forge.jar
[ 01-09 11:47:52.802 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/FarmersDelight.jar
[ 01-09 11:47:53.020 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/i18nupdatemod.jar
[ 01-09 11:47:53.021 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Jei.jar
[ 01-09 11:47:53.091 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Jeiintegration.jar
[ 01-09 11:47:53.094 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Journeymap.jar
[ 01-09 11:47:53.694 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/JustEnoughCharacters.jar
[ 01-09 11:47:53.715 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/JustEnoughResources.jar
[ 01-09 11:47:53.735 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Mantle.jar
[ 01-09 11:47:53.809 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Mcw-furniture.jar
[ 01-09 11:47:53.931 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Minecolonies.jar
[ 01-09 11:47:57.507 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Paladin.jar
[ 01-09 11:47:57.920 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Pollen-forge.jar
[ 01-09 11:47:58.017 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Quark.jar
[ 01-09 11:47:58.778 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Spark.jar
[ 01-09 11:47:59.047 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Structurize.jar
[ 01-09 11:48:00.045 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/TConstruct.jar
[ 01-09 11:48:00.956 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Tinker_rapier.jar
[ 01-09 11:48:00.966 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/TinyChests.jar
[ 01-09 11:48:00.980 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Towers_of_the_wild.jar
[ 01-09 11:48:00.997 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/TwilightDelight.jar
[ 01-09 11:48:01.014 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Twilightforest.jar
[ 01-09 11:48:03.806 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Waystones.jar
[ 01-09 11:48:03.841 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/WegotRunners.jar
[ 01-09 11:48:03.855 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Worldedit.jar
[ 01-09 11:48:04.327 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/mods/Wyrmroost.jar
[ 01-09 11:48:04.766 INFO  ] [McPatchClient/BasePack] Fill: .minecraft/versions/***-1.16.5/servers.dat
[ 01-09 11:48:04.784 INFO  ] [McPatchClient/BasePack] ========== changelogs for version BasePack ==========
[ 01-09 11:48:04.793 INFO  ] [McPatchClient/BasePack] |No change logs for the version BasePack
[ 01-09 11:48:04.793 INFO  ] [McPatchClient/BasePack] 
[ 01-09 11:48:04.793 DEBUG ] [McPatchClient/230109] old files: .minecraft/versions/***-1.16.5/mods/Spark.jar
[ 01-09 11:48:04.794 DEBUG ] [McPatchClient/230109] new files: .minecraft/versions/***-1.16.5/mods/spark.jar|m|e535ad75bb2f541ea8c9ad3fda5da9b3241c2575|e535ad75bb2f541ea8c9ad3fda5da9b3241c2575|cd9f96f325f7bd4f9ec177b466fd0a95fdfbbdb6|fd40dd8a0b168c5456387cfa703830f1235ec3c5|b8|58|302c79
[ 01-09 11:48:04.795 DEBUG ] [McPatchClient/230109] http request on https://files.***/d/MCUpdate/test/230109.mc-patch.bin, write to: C:/Users/i/AppData/Local/Temp/mc-patch-2301093804974369420844087.bin
[ 01-09 11:48:06.079 DEBUG ] [McPatchClient/230109] calculating the hash of the patch file
[ 01-09 11:48:06.081 INFO  ] [McPatchClient/230109] Modify: .minecraft/versions/***-1.16.5/mods/spark.jar (skip because the old file not found)
[ 01-09 11:48:06.082 INFO  ] [McPatchClient/230109] ========== changelogs for version 230109 ==========
[ 01-09 11:48:06.082 INFO  ] [McPatchClient/230109] |No change logs for the version 230109
[ 01-09 11:48:06.083 INFO  ] [McPatchClient/230109] 
[ 01-09 11:48:06.084 INFO  ] [McPatchClient] successfully applied these versions：[BasePack, 230109]
[ 01-09 11:48:06.085 INFO  ] [McPatchClient] continue to start Minecraft!
[ 01-09 11:48:06.094 INFO  ] [McPatchClient] RAM: 121.83 MB
[ 01-09 11:48:06.094 INFO  ] [McPatchClient] finished!

**Comment by asforest** [comment]
此问题是由于Windows平台文件名大小写不敏感造成的，在其它平台则都是大小写敏感的。
在Windows平台使用McPatchManage的过程中尽量避免这种修改大小写的行为

**Comment by asforest** [comment]
这个问题准确来说是管理端的问题，而非客户端。我后面会尝试在管理端添加验证，避免出现这种修改大小写的文件进入更新包

**Comment by asforest** [comment]
此问题已经在管理端 1.1.9 版本中解决，出现大小写不同的同名文件时，管理端会直接终止打包过程，防止有问题的数据进入更新包里。

https://github.com/BalloonUpdate/McPatchManage/releases/tag/v1.1.9
