### ISSUE TITLE
处理 codeql 扫描出来的潜在漏洞

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [BalloonUpdate/McPatchClient#10]
如题，code ql 检测出了4个潜在漏洞，待解决。
sha1处理方案：再加一个 md5 校验，这样会导致碰撞基本不可能实现。

**Comment by asforest** [comment]
需要考虑性能开销，尤其是移动端设备性能非常敏感。碰撞概率虽然减小了，但性能负担加大了不少，我认为是不值得的

**Comment by Mr-Ao-Dragon** [comment]
> 需要考虑性能开销，尤其是移动端设备性能非常敏感。碰撞概率虽然减小了，但性能负担加大了不少，我认为是不值得的

好吧，可以。
