### ISSUE TITLE
[特性请求] 更新一次性更新全部，更新日志只汇总展示一次

### ISSUE THREAD

**Issue by SettingDust** [BalloonUpdate/McPatchClient#13]
现在每个补丁都要确定一次有些麻烦
希望是所有日志汇总到一次显示，版本号分段，带滚动条，只需要确定一次

**Comment by asforest** [comment]
已加入开发计划

**Comment by asforest** [comment]
已在 1.0.15 版本中实现。 https://github.com/BalloonUpdate/McPatchClient/releases/tag/v1.0.15
