### ISSUE TITLE
多线程下载支持

### ISSUE THREAD

**Issue by asforest** [BalloonUpdate/McPatchClient#2]
多线程下载可有效提高更新速度，尤其是对于自由化部署。

**Comment by Mr-Ao-Dragon** [comment]
可能的解决方法: libaria2，升级到quic

**Comment by asforest** [comment]
libaria2和quic都是http技术栈。软件并非只支持http协议，还sftp协议，这些协议libaria2和quic无能为力

**Comment by Mr-Ao-Dragon** [comment]
> libaria2和quic都是http技术栈。软件并非只支持http协议，还sftp协议，这些协议libaria2和quic无能为力

对于多线程的sftp 有一个替代品：librsync

**Comment by asforest** [comment]
librsync是一个c库，加载很麻烦。另外rsync库有很多功能用不上，它主要是做文件同步的。McPatch需要的是针对单文件的多线程下载，不清楚librsync是否支持这个

**Comment by Mr-Ao-Dragon** [comment]
> librsync是一个c库，加载很麻烦。另外rsync库有很多功能用不上，它主要是做文件同步的。McPatch需要的是针对单文件的多线程下载，不清楚librsync是否支持这个

emm，我回头看看有没有更轻便的走ssh的库吧，最好是golang的

**Comment by asforest** [comment]
sftp的多线程不重要，用的人很少，暂时别考虑了吧。可以先考虑http(s)的多线程，sftp的等有人催再做吧 🤣

**Comment by Mr-Ao-Dragon** [comment]
我想也是

**Comment by Mr-Ao-Dragon** [comment]
新想法：先做并行下载，即多个更新包一起下载，最后所有更新包下载完后逐个应用
