### ISSUE TITLE
在获取包文件时，自动填写来源，便于进一步筛选非 McPatchClient 客户端。

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [BalloonUpdate/McPatchClient#23]
如题，可以进一步提高CC攻击成本，只需要指定来源可访问，攻击者就需要修改http包头，极大拉高攻击成本

**Comment by asforest** [comment]
[客户端1.1.3版本](https://github.com/BalloonUpdate/McPatchClient/releases/tag/v1.1.3)支持自定义http头了，已经可以实现简单鉴权机制。

另外修改http头对攻击者来说不是什么难事，很容易就能办到

---

利用自定义http头验证需要服务端的配合，这个issue开到服务端会比较合适

**Comment by asforest** [comment]
客户端1.1.3版本已经支持自定义http头功能
