### ISSUE TITLE
webdav源更新时文件大小不对

### ISSUE THREAD

**Issue by 1zyao** [BalloonUpdate/McPatchClient#26]
webdav源更新时文件大小不对 会显示成1GB 实际上100MB都不到

**Comment by asforest** [comment]
用的是什么webdav源？
如果服务器没有报告文件大小的话，默认就会显示成1gb，这是个兜底的做法

**Comment by 1zyao** [comment]
https://infini-cloud.net/ 的 浏览器下文件也不显示大小 但是速度显示正常 mcpatch下载时显示速度一会几百mb一会几kb 还显示负数

**Comment by asforest** [comment]
看来是服务器没有在协议里报告文件的具体大小，这种情况McPatch就会假定文件是1Gb大小，这是服务器的问题，如果服务器不报告文件大小，就没法显示精确的进度条。

另外速度不稳定是已知的bug，复现比较困难，短期内无法修复

**Comment by 1zyao** [comment]
我可以提供配置文件

**Comment by asforest** [comment]
这个问题问题出现的随机性极大，我已经试过很多方法了都无法重现，目前来看和客户端运行环境有关，和服务器没有明显因果关系

**Comment by asforest** [comment]
> 如果下载服务器无法指定文件大小，客户端方面可否手动指定文件大小？ @asforest

目前是代码里写死的1GB大小，无法通过配置文件去修改。

更新包的大小不是固定的，即使可以配置效果也不会太好。最好是由服务器报告文件大小，这是最优解。

**Comment by asforest** [comment]
> > > 如果下载服务器无法指定文件大小，客户端方面可否手动指定文件大小？ @asforest
> > 
> > 
> > 目前是代码里写死的1GB大小，无法通过配置文件去修改
> 
> 希望可以增加这个功能，谢谢

可以

**Comment by 1zyao** [comment]
java -version
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)



https://github.com/BalloonUpdate/McPatchClient/assets/107829654/b3d1f2a3-4dc9-448b-b1a2-a732aa605d43


配置塞jar里了：
[新建压缩文件.zip](https://github.com/BalloonUpdate/McPatchClient/files/12093049/default.zip)

**Comment by asforest** [comment]
@xiaozhu2007 已经实现在了客户端1.1.10版本，可以通过配置文件修改

https://github.com/BalloonUpdate/McPatchClient/releases/tag/v1.1.10

**Comment by asforest** [comment]
@1zyao  已经在客户端1.1.10版本里修复了速度显示的问题。（但有时候也会有莫名的限速问题，这个隐藏bug暂时无法修复）

https://github.com/BalloonUpdate/McPatchClient/releases/tag/v1.1.10

**Comment by asforest** [comment]
问题已解决，如有问题请重新开启这个Issue
