### ISSUE TITLE
stream is not in the bzip2 format

### ISSUE THREAD

**Issue by QWXL** [BalloonUpdate/McPatchClient#27]
![{E92E9E70-7AFF-0015-78B1-A3AAEF4197F8}](https://github.com/BalloonUpdate/McPatchClient/assets/82765188/1d581603-03d7-4669-beb8-f7b8c3c21aff)
不知道发生了什么，版本1.1.12

**Comment by asforest** [comment]
复现这个问题的步骤是什么

**Comment by QWXL** [comment]
没有步骤，没有前兆，很莫名其妙

**Comment by QWXL** [comment]
> 复现这个问题的步骤是什么


没有步骤，没有前兆，很莫名其妙

**Comment by QWXL** [comment]
> 复现这个问题的步骤是什么


没有步骤，没有前兆，很莫名其妙

**Comment by asforest** [comment]
那是怎么触发的，出现这个问题之前都做了什么操作

**Comment by QWXL** [comment]
> 

我在管理端发布了更新包，随后要求我的玩家们下载，但绝大多数人都出现了这样的问题，仅在尝试多次后才有极少数人成功

**Comment by asforest** [comment]
那个出问题的更新包方便在这里发一份吗

**Comment by QWXL** [comment]
[NewPack2.0_F3_A-T.mcpatch.zip](https://github.com/BalloonUpdate/McPatchClient/files/12291524/NewPack2.0_F3_A-T.mcpatch.zip)
是在自家的apache服务上挂着的

> 那个出问题的更新包方便在这里发一份吗

**Comment by asforest** [comment]
在管理端输入命令t之后的测试能通过吗

**Comment by QWXL** [comment]
> 在管理端输入命令t之后的测试能通过吗

[NewPack2.0_A-T] 验证文件(104/106): .minecraft/versions/TrainTownONLINE NewPack/mods/[镁／铷：附属] rubidium_extras-1.18.2_v1.3.2.jar
[NewPack2.0_A-T] 验证文件(105/106): .minecraft/versions/TrainTownONLINE NewPack/PCL/Logo.png
[NewPack2.0_A-T] 验证文件(106/106): .minecraft/versions/TrainTownONLINE NewPack/PCL/Setup.ini
Exception in thread "main" java.io.IOException: Stream is not in the BZip2 format
        at org.apache.tools.bzip2.CBZip2InputStream.init(CBZip2InputStream.java:287)
        at org.apache.tools.bzip2.CBZip2InputStream.<init>(CBZip2InputStream.java:162)
        at org.apache.tools.bzip2.CBZip2InputStream.<init>(CBZip2InputStream.java:129)
        at mcpatch.core.PatchFileReader$PatchEntry.getInputStream(PatchFileReader.kt:70)
        at mcpatch.core.PatchFileReader$PatchEntry.copyTo(PatchFileReader.kt:84)
        at mcpatch.interactive.Test.execute(Test.kt:33)
        at mcpatch.McPatchManage.main(McPatchManage.kt:75)

**Comment by asforest** [comment]
方便把NewPack2.0_A-T这个更新包发一份吗

**Comment by asforest** [comment]
试一下这个版本的t命令是否能y验证通过（需要删掉文件名后面的.zip)

[McPatchManage-0.0.0.jar.zip](https://github.com/BalloonUpdate/McPatchClient/files/12292038/McPatchManage-0.0.0.jar.zip)

**Comment by QWXL** [comment]
> 方便把NewPack2.0_A-T这个更新包发一份吗

过大，传不上github

**Comment by QWXL** [comment]
> 试一下这个版本的t命令是否能y验证通过（需要删掉文件名后面的.zip)
> 
> [McPatchManage-0.0.0.jar.zip](https://github.com/BalloonUpdate/McPatchClient/files/12292038/McPatchManage-0.0.0.jar.zip)

ok我试一下

**Comment by QWXL** [comment]
> 试一下这个版本的t命令是否能y验证通过（需要删掉文件名后面的.zip)
> 
> [McPatchManage-0.0.0.jar.zip](https://github.com/BalloonUpdate/McPatchClient/files/12292038/McPatchManage-0.0.0.jar.zip)

不行，问题依旧

**Comment by asforest** [comment]
有没有手动编辑过NewPack2.0_A-T更新包里面的文件

**Comment by asforest** [comment]
如果没有编辑过，删掉这个版本重写打包

**Comment by asforest** [comment]
把`NewPack2.0_A-T`更新包中的`.minecraft/versions/TrainTownONLINE NewPack/PCL/Setup.ini`文件解压出来截个图看看（截图文件的内容）

**Comment by QWXL** [comment]
> 把`NewPack2.0_A-T`更新包中的`.minecraft/versions/TrainTownONLINE NewPack/PCL/Setup.ini`文件解压出来截个图看看（截图文件的内容）

![image](https://github.com/BalloonUpdate/McPatchClient/assets/82765188/470d1e1c-f7a5-410e-830a-02e2176e93bd)

**Comment by QWXL** [comment]
特殊字符（𝙏𝙧𝙖𝙞𝙣𝙏𝙤𝙬𝙣 𝙊𝙉𝙇𝙄𝙉𝙀之类的）应该不会影响打包吧

**Comment by asforest** [comment]
特殊字符不会

**Comment by asforest** [comment]
看样子你是手动修改过更新包的文件对吗

**Comment by QWXL** [comment]
是

**Comment by asforest** [comment]
> > 复现这个问题的步骤是什么
> 
> 没有步骤，没有前兆，很莫名其妙

你不是说没有做过任何步骤吗，到底哪个是真的

**Comment by QWXL** [comment]
嘛，我一开始投issue不是认为这是个客户端问题嘛，所以一开始的“没有步骤”是指客户端，因为也有玩家更新成功了，所以没往管理端想

**Comment by asforest** [comment]
这个不是管理端的问题也不是客户端的问题，是你手动修改更新包问题。

更新包里的文件虽然保持原有路径结构，但都是压缩过的，你直接替换一个没有压缩过的当然会出问题。所以不要手动修改里面的任何文件，除非你很清楚更新包里面的存储格式！

另外这个包是有问题的，玩家绝对不可能更新成功（因为你管理端测试都不通过）。要么他们更新的不是这个版本，要么就是他们乱说的。

解决办法：参考文档：[版本发错了怎么办](https://balloonupdate.github.io/McPatchDocs/tutorial-notices.html#%E7%89%88%E6%9C%AC%E5%8F%91%E9%94%99%E4%BA%86%E6%80%8E%E4%B9%88%E5%8A%9E)撤回这个有问题的包就行了

**Comment by QWXL** [comment]
彳亍，不好意思

**Comment by asforest** [comment]
如有问题请再次开启此Issue
