### ISSUE TITLE
发布Issue前必读

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [BalloonUpdate/McPatchClient#6]
- 没有人有义务对此程序的问题负责。
- 您应该知晓开源=贡献者享有免责权力，他们在道德上无可指摘，除非违反了法律或触及底线。
- 请尊重所有人。
- 修复问题是贡献者愿意行使的权力，而不是必须承担的义务。
- 我们不会对触及底线和违反当地法律的问题做任何回答，也不会做任何技术支持。

**Comment by asforest** [comment]
此规定意义不大。愿意遵守的人不需要看，看的人不一定会遵守
