### ISSUE TITLE
添加quic协议支持

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [BalloonUpdate/McPatchClient#7]
quic协议是一个高性能，高安全的协议，可大大提升传输速度。

**Comment by asforest** [comment]
quic协议使用udp通信，对某些防火墙不太友好，增加支持的问题还有待商讨。
目前的HTTPS足以应付95%的使用场景，quic在这些场景并没有特别显著的优点

**Comment by Mr-Ao-Dragon** [comment]
> quic协议使用udp通信，对某些防火墙不太友好，增加支持的问题还有待商讨。
> 目前的HTTPS足以应付95%的使用场景，quic在这些场景并没有特别显著的优点

quic自带多线程，这样很多时候http多线程就不用开了，另外现代防火墙都有udp放行了，包括一些老设备。

**Comment by asforest** [comment]
暂不考虑quic，在当前使用场景下quic相较于http(s)没有特别明显的优势
