### ISSUE TITLE
为推送请求启用强制性构建检查

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [BalloonUpdate/McPatchClient#8]
如题，为了防止无法通过编译的问题蒙混过关，需要打开必须通过自动actions检查后才能合并。

**Comment by asforest** [comment]
目前的Actions脚本有问题，使用zulu17编译会导致使用所有使用低版本的Minecraft无法启动，因为低版本Java无法识别高版本字节码格式

**Comment by Mr-Ao-Dragon** [comment]
好的，我这就改

**Comment by asforest** [comment]
已开启
