### ISSUE TITLE
编写Issue模板

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [BalloonUpdate/McPatchClient#9]
Issue模板可有效规范并分类Issue，对于不懂github工作流的人来说非常有用。

**Comment by asforest** [comment]
Issue模板用处不大，大部分人遇到问题会直接在群里反馈问题，沟通效率更高，不会专门开issue提问
不懂github工作流的人不建议来issue提问，沟通效率低下，issue无法发送录屏等关键信息，群里问会更快
这个软件目前暂不考虑国外用户，所以大部分沟通都是在QQ群里进行的

如果以后有这个需求再重开此issue
